---
- name: Initialize Docker Swarm (only on svr1)
  ansible.builtin.shell: |
    docker swarm init --advertise-addr {{ ansible_host }}
  when: inventory_hostname == 'svr1'

- name: Get the Swarm join token
  ansible.builtin.command: docker swarm join-token worker -q
  register: swarm_token
  when: inventory_hostname == 'svr1'

- name: Join Swarm as worker
  ansible.builtin.shell: |
    docker swarm join --token {{ hostvars['svr1']['swarm_token'].stdout }} {{ hostvars['svr1']['ansible_host'] }}:2377
  when: inventory_hostname != 'svr1'

- name: Deploy Portainer stack
  ansible.builtin.copy:
    src: templates/portainer-stack.yml
    dest: /opt/portainer-stack.yml

- name: Deploy Portainer stack to Swarm
  ansible.builtin.shell: docker stack deploy -c /opt/portainer-stack.yml portainer

- name: Deploy Traefik stack
  ansible.builtin.copy:
    src: templates/traefik-stack.yml
    dest: /opt/traefik-stack.yml

- name: Deploy Traefik stack to Swarm
  ansible.builtin.shell: docker stack deploy -c /opt/traefik-stack.yml traefik
